import ObjectWithFallback from '../types/objectWithFallback';

export const columnNamesPL = new ObjectWithFallback<string>(
  {
    id: 'ID',
    firstName: 'Imię',
    lastName: 'Nazwisko',
    email: 'E-Mail',
    yearOfBirth: 'Rocznik',
    gender: 'Płeć',
    hasAccount: 'Konto',
    isPZAMember: 'PZA',
    isClubMember: 'Skarpa/SP28',
    clubName: 'Klub',
    createdAt: 'Data dodania',
    updatedAt: 'Data modyfikacji',
    name: 'Nazwa',
    seq: 'L.p.',
    minAge: 'Wiek Min.',
    maxAge: 'Wiek Max.',
    authLevel: 'Poziom upr.',
    description: 'Opis',
    lockResults: 'Zablokuj wyniki',
    lockEnroll: 'Zablokuj zapisy',
    allowFamilyRanking: 'Rodzinna',
    clubMembersPay: 'Członkowie płacą',
    isInternal: 'Wewnętrzne',
    startDate: 'Rozpoczęcie zawodów',
    endDate: 'Zakończenie zawodów',
    enrollStart: 'Rozpoczęcie zapisów',
    enrollEnd: 'Zakończenie zapisów',
    startNumber: 'Numer',
    requestsFamilyRanking: 'Rodzinna',
    hasPaid: 'Opłacono',
    underageConsent: 'Oświadczenie -18',
    verified: 'Zweryfikowany',
    shortName: 'Skrót',
    score: 'Punkty',
    fromTime: 'Od',
    toTime: 'Do',
    roleId: 'Rola',
    user: 'Użytkownik',
    category: 'Kategoria',
    taskStaff: 'Sędzia',
    verificationStaff: 'Weryfikator',
    task: 'Zadanie',
    userCompetition: 'Zapis',
    family: 'Rodzina',
    flags: 'Flagi',
    categories: 'Kategorie',
    type: 'Typ',
  },
  'N/A'
);
