import { ThemeProvider } from '@material-tailwind/react';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="m-0 p-0 min-h-screen">
      <body className="m-0 p-0 w-full min-h-screen">
        <ThemeProvider value={{}}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
